<div class="gallery">
            <section class="col-md-12">
                <div id="gallery_search_form" class="gallery_search">
                    <ng-form data-script="searchGallery" action="?" id="filter_gallery" class="ajaxForm europaForm">
                        <div class="container-fluid row" id="searchHeader">
                            <div class="col-md-6">
                                <h2>Product Gallery</h2>
                            </div>
                        </div>




                        <div class="container-fluid row" id="searchFieldContainer">
                          <fieldset id="style_options" class="searchField col-md-4">
                            <h2>Style</h2>
                            <select class="door-filters" id="styles">
                              <option value="All">All</option>
                              <option value="Traditional">Traditional</option>
                              <option value="Contemporary">Contemporary</option>
                              <option value="Transitional">Transitional</option>
                              <option value="Modern">Modern</option>
                              <option value="Arts and Crafts">Arts and Crafts</option>
                              <option value="Southwest">Southwest</option>
                            </select>
                          </fieldset>
                          <fieldset id="material_options" class="searchField col-md-4">
                            <h2 value="Material">Material</h2>
                            <select class="door-filters" id="materials">
                              <option value="All">All</option>
                              <option value="Wood">Wood</option>
                              <option value="Thermofoil">Thermofoil</option>
                              <option value="Melamine">Melamine</option>
                              <option value="Metal">Metal</option>
                              <option value="UltraLux">UltraLux</option>
                              <option value="Eurotek Veneer">Eurotek Veneer</option>
                              <option value="Deluxe Veneers">Deluxe Veneers</option>
                            </select>
                          </fieldset>
                          <fieldset id="construction_options" class="searchField col-md-4">
                            <h2>Door Construction</h2>
                            <select class="door-filters" id="construction">
                              <option value="All">All</option>
                              <option value="Raised Pane">Raised Pane</option>
                              <option value="Recessed Panel">Recessed Panel</option>
                              <option value="Slab">Slab</option>
                            </select>
                          </fieldset>
                        </div>







                    </ng-form>
                </div>
            </section>
            <div id="products_area" class="col-md-12 row">

            <div class="col-md-4 mt-3 door-card" data-styles="Contemporary,Modern" data-materials="UltraLux" data-construction="Slab"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=3"><img class="door_img" style="width:79px; height:160px;" src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0158.jpg" alt="Acrilux"></a></div><div class="text_area"><div class="prod_name">Acrilux</div><div class="prod_desc"><div class="ExternalClass99AFF174507F4C5287EAD6F1DC9384B2"><p>&#8203;3/4"-thick, slab door and drawer front. Door is edgebanded&nbsp;in
translucent PVC with an aluminum backer. UltraLux finishes (with the
exception of the Linear options) are scratch-resistant.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Contemporary,Modern" data-materials="Thermofoil" data-construction="Slab"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=2"><img class="door_img" style="width:79px; height:160px;" src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0219.jpg" alt="Adriatic"></a></div><div class="text_area"><div class="prod_name">Adriatic</div><div class="prod_desc"><div class="ExternalClass5FBE2C75D26945B294DD44840F9EC2A5"><p>&#8203;&#8203;3/4"-thick, slab door and drawer front with eased outside edges.<br></p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Traditional,Transitional" data-materials="Wood" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=5"><img class="door_img" style="width:79px; height:160px;" src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0230.jpg" alt="Amherst"></a></div><div class="text_area"><div class="prod_name">Amherst</div><div class="prod_desc"><div class="ExternalClassBB166C5FBAB4472DA4BAE3299E2C53E0"><p>&#8203;3/4"-thick, mitered frame with beaded outside edge and beaded inside
edge detail. Solid wood, recessed center panel. 2-5/16" wide rails and
stiles</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Traditional,Transitional" data-materials="Wood" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=6"><img class="door_img" style="width:79px; height:160px;" src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0231.jpg" alt="Andover"></a></div><div class="text_area"><div class="prod_name">Andover</div><div class="prod_desc"><div class="ExternalClass427DB3133BFD42B38073F33C9F8E0C57"><p>&#8203;3/4"-thick, mortise-and-tenon frame with eased outside edge&nbsp;and applied
molding detail. Veneer, recessed center panel.&nbsp;2-5/16" wide rails and
stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Contemporary,Modern" data-materials="Wood" data-construction="Slab"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=7"><img class="door_img" style="width:79px; height:160px;" src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0125.jpg" alt="Apex"></a></div><div class="text_area"><div class="prod_name">Apex</div><div class="prod_desc"><div class="ExternalClass84CB625CEC4C44228628A73F428DC663"><p>&#8203;3/4"-thick slab door with eased outside edge profile.&nbsp;Constructed of Medium Density Fiberboard.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Traditional" data-materials="Wood" data-construction="Raised Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=8"><img class="door_img" style="width:79px; height:160px;" src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0233.jpg" alt="Asheville"></a></div><div class="text_area"><div class="prod_name">Asheville</div><div class="prod_desc"><div class="ExternalClassB125D89B4E6A43C1892BD2BE8C81033A"><p>&#8203;3/4"-thick, mortise-and-tenon frame with ogee outside edge.&nbsp;Solid wood, raised center panel. 2-5/16" wide rails and stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Arts and Crafts,Contemporary,Transitional" data-materials="Wood" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=9"><img class="door_img" style="width:79px; height:160px;" src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0153.jpg" alt="Avon"></a></div><div class="text_area"><div class="prod_name">Avon</div><div class="prod_desc"><div class="ExternalClass0E1D134B84C44D3380E0F8311D25A186"><p>&#8203;3/4"-thick, mortise-and-tenon frame with inside beveled edges and eased
outside edge. Veneer, recessed center panel. 2-5/16" wide rails and
stiles. Slab drawer front standard, 5-piece Matching Drawer Front
optional.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Arts and Crafts,Contemporary,Transitional" data-materials="Wood" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=100"><img class="door_img" style="width:79px; height:160px;" src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/Avon%20Wide%20-%205%20pc%20-%20Arctic%20White%20-%20Flat.jpg" alt="Avon Wide"></a></div><div class="text_area"><div class="prod_name">Avon Wide</div><div class="prod_desc"><div class="ExternalClass1C8205859BC947C8912F4A427F29A1E8"><p>&#8203;<span style="color:#666666;font-family:lato, sans-serif;font-size:12.8px;background-color:#ffffff;">3/4"-thick, mortise-and-tenon frame with inside beveled edges and eased outside edge. Veneer, recessed center panel. 3-1/2" wide rails and stiles. Slab drawer front standard, 5-piece Matching Drawer Front optional.</span><br></p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Traditional" data-materials="Thermofoil" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=10"><img class="door_img" style="width:79px; height:160px;" src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0234.jpg" alt="Beadboard"></a></div><div class="text_area"><div class="prod_name">Beadboard</div><div class="prod_desc"><div class="ExternalClass3D7F6A806E8F4B0CA739DF1A24DAE8C3"><p>&#8203;3/4"-thick door with eased outside edge detail and slanted bevel
on&nbsp;inside edge. Recessed center panel has double-grooved beaded&nbsp;detail.
2" wide rails and stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Contemporary,Transitional" data-materials="Wood" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=12"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0238.jpg" alt="Boca Raton"></a></div><div class="text_area"><div class="prod_name">Boca Raton</div><div class="prod_desc"><div class="ExternalClassCAE0177ACD52436B891C5A317E134D78"><p>&#8203;3/4"-thick, mortise-and-tenon frame with 1/8" round-over edge
and&nbsp;waterfall inside edge detail. Flat veneer, recessed center
panel.&nbsp;2-3/4" wide rails and stiles. </p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Traditional" data-materials="Wood" data-construction="Raised Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=13"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0240.jpg" alt="Boston"></a></div><div class="text_area"><div class="prod_name">Boston</div><div class="prod_desc"><div class="ExternalClass66B4E50DAE434B45B2D3DFF4E7376254"><p>&#8203;3/4"-thick, mortise-and-tenon frame with ogee detail on&nbsp;outside edge.
Solid wood, slant-bevel, raised center&nbsp;panel.&nbsp;2-5/16" wide rails and
stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Traditional,Transitional" data-materials="Wood" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=16"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0245.jpg" alt="Breckenridge"></a></div><div class="text_area"><div class="prod_name">Breckenridge</div><div class="prod_desc"><div class="ExternalClass01DC04A02CC14B5FB79194D990672D56"><p>&#8203;3/4"-thick, mortise-and-tenon frame with eased outside edge&nbsp;and beaded
inside edge detail. Solid wood, recessed center&nbsp;panel. 2-5/16" wide
rails and stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Traditional,Transitional" data-materials="Wood" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=17"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0248.jpg" alt="Breckenridge Wide"></a></div><div class="text_area"><div class="prod_name">Breckenridge Wide</div><div class="prod_desc"><div class="ExternalClass630641099F0742DCB935B804C8F01640"><p>&#8203;3/4"-thick, mortise-and-tenon frame with eased outside edge,&nbsp;beaded
inside edge detail, and 3-1/2" wide rails and stiles.&nbsp;Solid wood,
recessed center panel.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Arts and Crafts,Contemporary,Transitional" data-materials="Wood" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=18"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0155.jpg" alt="Bristol"></a></div><div class="text_area"><div class="prod_name">Bristol</div><div class="prod_desc"><div class="ExternalClass0B4D4341A7704A779E3969F4147B4FB4"><p>&#8203;3/4"-thick, mortise-and-tenon frame with eased outside edge and beaded
inside edge detail. Veneer, recessed center panel. 2-5/16" wide rails
and stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Contemporary,Modern" data-materials="Metal" data-construction="Slab"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=19"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0117.jpg" alt="Broadline Aluminum"></a></div><div class="text_area"><div class="prod_name">Broadline Aluminum</div><div class="prod_desc"><div class="ExternalClass85AA7BCCE96946AB899D949A1CB40E00"><p>&#8203;3/4"-thick, mitered door with 21/8˝ square edge rails and&nbsp;stiles. Door comes in frame-style only with a choice of&nbsp;glass inserts.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Contemporary,Modern" data-materials="Metal" data-construction="Slab"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=20"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0118.jpg" alt="Broadline Stainless Steel"></a></div><div class="text_area"><div class="prod_name">Broadline Stainless Steel</div><div class="prod_desc"><div class="ExternalClass82269A95973A43509C8ADF591B04E17B"><p>&#8203;3/4"-thick, mitered door with 21/8˝ square edge rails and&nbsp;stiles. Door comes in frame-style only with a choice of&nbsp;glass inserts.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Contemporary,Transitional" data-materials="Wood" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=21"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0207.jpg" alt="Broadview"></a></div><div class="text_area"><div class="prod_name">Broadview</div><div class="prod_desc"><div class="ExternalClass5F0D9A2A1FF44C209A334C8CB4A7ED0A"><p>&#8203;3/4"-thick, mitered frame with eased outside edges and&nbsp;beaded inside
edge detail. Solid wood, recessed center&nbsp;panel with 2-5/16" wide rails
and stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Traditional" data-materials="Wood" data-construction="Raised Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=22"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0072.jpg" alt="Brunswick"></a></div><div class="text_area"><div class="prod_name">Brunswick</div><div class="prod_desc"><div class="ExternalClassEE6BD3351B07470F9C272B465FE1D487"><p>&#8203;3/4"-thick, mitered frame with beaded outside edge and beaded&nbsp;inside
edge detail. Solid wood, slant-bevel raised center panel.&nbsp;2-5/16" wide
rails and stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Contemporary,Modern,Transitional" data-materials="Eurotek Veneer" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=23"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0256.jpg" alt="Cape May"></a></div><div class="text_area"><div class="prod_name">Cape May</div><div class="prod_desc"><div class="ExternalClassD24E1191ACC3467BA7E8E4EB0135F437"><p>&#8203;3/4"-thick, recessed-panel door with eased outside edges, and 3"-wide
rails and stiles. Standard front panel is 3/4"-thick Coordinated
Eurotek. Comes standard with a 5-piece matching drawer front. Slab
drawer fronts are not available.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Traditional" data-materials="Wood" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=24"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0071.jpg" alt="Carnegie"></a></div><div class="text_area"><div class="prod_name">Carnegie</div><div class="prod_desc"><div class="ExternalClass0F94DC58E2BC44E59EA61A77EFC6ABF7"><p>&#8203;3/4"-thick, mitered frame with beaded outside edge and&nbsp;rope and bead
inside edge detail. Veneer, recessed center&nbsp;panel. 2-5/16" wide rails
and stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Contemporary,Modern" data-materials="Thermofoil" data-construction="Slab"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=25"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0065.jpg" alt="Cellini"></a></div><div class="text_area"><div class="prod_name">Cellini</div><div class="prod_desc"><div class="ExternalClassF6013BF1C4B844769EB79AA251CB3397"><p>&#8203;3/4"-thick, slab door and drawer front. Outside edges&nbsp;bevel from 3/4" to 5/8".</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Traditional" data-materials="Thermofoil" data-construction="Raised Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=26"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0171.jpg" alt="Charleston Wide"></a></div><div class="text_area"><div class="prod_name">Charleston Wide</div><div class="prod_desc"><div class="ExternalClass963CDCC42AEA426284F0270A6ADFE6C3"><p>&#8203;3/4"-thick, cove-bevel, raised-panel door and recessed-panel
drawer&nbsp;front,&nbsp;each with applied molding detail. 31⁄2"-wide rails and
stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Traditional" data-materials="Wood" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=27"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0069.jpg" alt="Charlotte"></a></div><div class="text_area"><div class="prod_name">Charlotte</div><div class="prod_desc"><div class="ExternalClass2B847F759D1140528F46DCDA1DA14736"><p>&#8203;3/4"-thick, mitered frame with ogee detail on outside edge and&nbsp;stepped,
beaded inside edge detail. Veneer, recessed center&nbsp;panel. 2-5/16" wide
rails and stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Contemporary,Transitional" data-materials="Wood" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=28"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0210.jpg" alt="Chesapeake"></a></div><div class="text_area"><div class="prod_name">Chesapeake</div><div class="prod_desc"><div class="ExternalClassDCCAC64036EF4A56ACCA69F0D259F1B1"><p>&#8203;3/4"-thick, mitered frame with eased outside edges and&nbsp;beaded inside
edge detail. Recessed veneer center&nbsp;panel with 2-5/16" wide rails and
stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Arts and Crafts,Contemporary,Transitional" data-materials="Eurotek Veneer" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=103"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/Eurotek%20-%20Clermont%20-%20Espresso%20-%20Flat.jpg" alt="Clermont"></a></div><div class="text_area"><div class="prod_name">Clermont</div><div class="prod_desc"><div class="ExternalClass658EFABE4F02463097F12A7FB3E15D5F"><p>3/4"-thick, recessed-panel door with eased outside&nbsp;edges, and 21/4"-wide rails and stiles.</p><p><br></p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Arts and Crafts,Contemporary,Southwest,Transitional" data-materials="Wood" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=29"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0034.jpg" alt="Corona"></a></div><div class="text_area"><div class="prod_name">Corona</div><div class="prod_desc"><div class="ExternalClass1555048E7E0A4B23B85C53249AA7FE50"><p>&#8203;3/4"-thick, mitered frame with eased outside edge and&nbsp;stepped inside
edge detail. Solid wood, recessed center panel.&nbsp;2-5/16" wide rails and
stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Contemporary,Traditional,Transitional" data-materials="Wood" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=30"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0129.jpg" alt="Crystal Lake"></a></div><div class="text_area"><div class="prod_name">Crystal Lake</div><div class="prod_desc"><div class="ExternalClassDD92C8D461BB40A6AD8CDC8F455883F2"><p>&#8203;3/4"-thick, mitered frame with eased edge and&nbsp;molded door profile. Solid wood, recessed center&nbsp;panel. 3" wide rails and stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Traditional,Transitional" data-materials="Wood" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=31"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0032.jpg" alt="Daytona"></a></div><div class="text_area"><div class="prod_name">Daytona</div><div class="prod_desc"><div class="ExternalClassDF4106D2AED342C3B0F2161FCC1830F5"><p>&#8203;3/4"-thick, mortise-and-tenon frame with ogee detail on outside&nbsp;edge and
 beaded inside edge detail. Veneer, recessed center&nbsp;panel. 2-5/16" wide
rails and stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Contemporary,Transitional" data-materials="Wood" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=32"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0030.jpg" alt="Dennison"></a></div><div class="text_area"><div class="prod_name">Dennison</div><div class="prod_desc"><div class="ExternalClass988792C3BA2845AD82F603C5024B9333"><p>&#8203;3/4"-thick, mitered frame with eased outside edge and&nbsp;double-beaded
inside edge detail. Veneer, recessed center&nbsp;panel. 2-5/16" wide rails
and stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Contemporary,Transitional" data-materials="Thermofoil" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=33"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0205.jpg" alt="Eastover"></a></div><div class="text_area"><div class="prod_name">Eastover</div><div class="prod_desc"><div class="ExternalClassE830E1760579403DB7B94315E1BD5F14"><p>&#8203;3/4"-thick, recessed center panel door and drawer front with&nbsp;eased
outside edge detail and large stepped bevel inside&nbsp;edge. 2-1/2" rails
and stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Contemporary,Modern" data-materials="UltraLux" data-construction="Slab"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=34"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0134.jpg" alt="Edgewater"></a></div><div class="text_area"><div class="prod_name">Edgewater</div><div class="prod_desc"><div class="ExternalClassB0C11DBC67BE454BB47D602698598D92"><p>&#8203;This UltraLux door features a High Gloss Acrylic front with a two-tone
laser edgebanding, creating a look that&nbsp;resembles backpainted glass
resting on an aluminum frame.&nbsp;UltraLux finishes (with the exception of
the Linear&nbsp;options) are scratch-resistant.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Contemporary,Modern" data-materials="Thermofoil" data-construction="Slab"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=35"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0157.jpg" alt="Edison"></a></div><div class="text_area"><div class="prod_name">Edison</div><div class="prod_desc"><div class="ExternalClassBB186484CBE64A2F9CE601C7AC9A9DEE"><p>&#8203;3/4"-thick, slab door and drawer front. Outside edges have a soft,&nbsp;beveled “pillow edge."</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Traditional,Transitional" data-materials="Wood" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=36"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0099.jpg" alt="Englewood"></a></div><div class="text_area"><div class="prod_name">Englewood</div><div class="prod_desc"><div class="ExternalClass8F01CD04372D43FD9E08509DD777BBB7"><p>&#8203;3/4"-thick, mortise-and-tenon frame with eased outside edge detail&nbsp;and
decorative inset applied molding. Wood veneer, recessed center&nbsp;panel
with 3" wide rails and stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Traditional,Transitional" data-materials="Wood" data-construction="Raised Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=37"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0249.jpg" alt="Evanston"></a></div><div class="text_area"><div class="prod_name">Evanston</div><div class="prod_desc"><div class="ExternalClass1EBA383392664449AE112804DFE6D050"><p>&#8203;3/4"-thick, mortise and tenon 1/2 raised panel door with RO outside
profile and beaded inside molding. Features a solid wood, two-step
raised center panel, with 2 5/16" wide rails and stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Traditional" data-materials="Wood" data-construction="Raised Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=38"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0022.jpg" alt="Fairlawn"></a></div><div class="text_area"><div class="prod_name">Fairlawn</div><div class="prod_desc"><div class="ExternalClass27D1450C15674DC09974BC4B43823DAB"><p>&#8203;3/4"-thick, mortise-and-tenon frame with ogee detail on&nbsp;outside and
inside edge. Solid wood, cove-bevel, raised&nbsp;center panel. 2-5/16" wide
rails and stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Contemporary,Modern" data-materials="Metal" data-construction="Slab"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=40"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0119.jpg" alt="Fineline Aluminum"></a></div><div class="text_area"><div class="prod_name">Fineline Aluminum</div><div class="prod_desc"><div class="ExternalClass697953A30FEF4249A69EE87EC464BB9F"><p>&#8203;3/4"-thick, mitered door with 1/16˝ square edge rails and&nbsp;stiles. Door comes in frame-style only with a choice of&nbsp;glass inserts.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Traditional,Transitional" data-materials="Wood" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=98"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0020.jpg" alt="Freedom"></a></div><div class="text_area"><div class="prod_name">Freedom</div><div class="prod_desc"><div class="ExternalClassFA1327096F9C4F59B549DF5750F37118"><p>&#8203;<span style="color:#333333;font-family:sans-serif, arial, verdana, &quot;trebuchet ms&quot;;background-color:#ffffff;">3/4"-thick, mitered frame with molded profile.&nbsp;Solid wood, slant-bevel, recessed center panel.&nbsp;2-7/8" wide rails and stiles.</span><br></p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Traditional,Transitional" data-materials="Wood" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=43"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0088.jpg" alt="Frisco"></a></div><div class="text_area"><div class="prod_name">Frisco</div><div class="prod_desc"><div class="ExternalClassD3C30D54CFD74885B3E481874DA1BB99"><p>&#8203;3/4"-thick, mitered and beaded frame with applied molding&nbsp;detail. Flat
veneer, recessed center panel. 21/4" wide rails and&nbsp;stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Traditional" data-materials="Thermofoil" data-construction="Raised Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=44"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0041.jpg" alt="Greco"></a></div><div class="text_area"><div class="prod_name">Greco</div><div class="prod_desc"><div class="ExternalClassBFF5D9D7A9114496817445382AF585DE"><p>&#8203;3/4"-thick, slant-bevel, raised-panel door and drawer front with
ogee&nbsp;detail on&nbsp;outside edges and bead detail on inside frame. 2-1⁄2"
wide&nbsp;rails and stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Traditional" data-materials="Thermofoil" data-construction="Raised Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=45"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0061.jpg" alt="Greco Wide"></a></div><div class="text_area"><div class="prod_name">Greco Wide</div><div class="prod_desc"><div class="ExternalClass3526F2D569754F5CADC9692E2E2DA40E"><p>&#8203;3/4"-thick, slant-bevel, raised-panel door and drawer front with
ogee&nbsp;detail on outside&nbsp;edges and bead detail on inside frame.
3-1⁄2"-wide rails and stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Traditional" data-materials="Wood" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=46"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0018.jpg" alt="Hampton"></a></div><div class="text_area"><div class="prod_name">Hampton</div><div class="prod_desc"><div class="ExternalClassD66B58ABB67C4285A2DED3DE164122A2"><p>&#8203;3/4"-thick, mortise-and-tenon frame with eased outside edge and&nbsp;beaded
inside edge detail. Solid wood, recessed center panel
with&nbsp;double-grooved beaded detail. 2-5/16" wide rails and stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Contemporary,Modern,Transitional" data-materials="UltraLux" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=47"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0255.jpg" alt="Hollywood"></a></div><div class="text_area"><div class="prod_name">Hollywood</div><div class="prod_desc"><div class="ExternalClassC954C70D271B4CF9AF6CEE6DF053AF2E"><p>&#8203;3/4"-thick, mortis and tenon door featuring 3" rails and stiles, with
matching edge-banding, around a flat center panel. Available prepared
for glass. Comes standard with a 5-piece matching drawer front.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Traditional,Transitional" data-materials="Thermofoil" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=48"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0179.jpg" alt="Hudson Wide"></a></div><div class="text_area"><div class="prod_name">Hudson Wide</div><div class="prod_desc"><div class="ExternalClass9049C2E941544EA7BF920F33BF56CFB1"><p>&#8203;3/4"-thick, recessed-panel door and drawer front with eased
outside&nbsp;edges and&nbsp;bead detail on inside frame. 3-1⁄2"-wide rails
and&nbsp;stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Arts and Crafts,Contemporary,Southwest,Transitional" data-materials="Eurotek Veneer" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=49"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0055.jpg" alt="Jamestown"></a></div><div class="text_area"><div class="prod_name">Jamestown</div><div class="prod_desc"><div class="ExternalClass8F0C91FB2A5F4E3CBFE60833E08274C0"><p>&#8203;3/4"-thick, recessed-panel door with eased outside&nbsp;edges, and 3-1⁄8"-wide rails and stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Contemporary,Modern" data-materials="Thermofoil" data-construction="Slab"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=50"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0039.jpg" alt="Jupiter"></a></div><div class="text_area"><div class="prod_name">Jupiter</div><div class="prod_desc"><div class="ExternalClassC226F7826CA44EC5AF75357E1D7BE079"><p>&#8203;3/4"-thick, slab door and drawer front. Outside edges bevel&nbsp;from 3/4" to 1/2" and are “pointed” on the corners.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Traditional" data-materials="Wood" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=51"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0259.jpg" alt="Kiawah"></a></div><div class="text_area"><div class="prod_name">Kiawah</div><div class="prod_desc"><div class="ExternalClass2BC9387029BE4814859DF51A6CE8633F"><p>&#8203;3/4"-thick, mortise-and-tenon frame with eased edges, and&nbsp;2" wide rails
and 2-1/4" wide stiles. Solid wood, louvered&nbsp;construction with solid
center panel.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Contemporary,Modern,Transitional" data-materials="Melamine" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=52"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0221.jpg" alt="Kitty Hawk"></a></div><div class="text_area"><div class="prod_name">Kitty Hawk</div><div class="prod_desc"><div class="ExternalClass64B6313600AF4C268CC697D2ABB61CD3"><p>&#8203;3/4"-thick, Textured Melamine, 5-piece door and optional 5-piece drawer
front feature 3˝ rails and stiles and a recessed center panel. Slab
drawer front with horizontal grain is standard.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Traditional" data-materials="Wood" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=53"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0212.jpg" alt="Lafayette"></a></div><div class="text_area"><div class="prod_name">Lafayette</div><div class="prod_desc"><div class="ExternalClass6787C350FAC64E92BFA48A49CBC4FB1B"><p>&#8203;3/4"-thick, mitered frame with notched outside edges&nbsp;and molded door
profile. Solid wood, recessed center&nbsp;panel with 2-1/2" wide rails and
stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Contemporary,Modern" data-materials="Eurotek Veneer" data-construction="Slab"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=104"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/Eurotek%20-%20Lakehurst%20-%20Bright%20White%20-%20Flat.jpg" alt="Lakehurst"></a></div><div class="text_area"><div class="prod_name">Lakehurst</div><div class="prod_desc"><div class="ExternalClassBB74ADFA4FFC4414AF5661F5347A27A3"><p>&#8203;3/4"-thick, slab door and drawer front with square edges.<br></p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Traditional" data-materials="Wood" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=54"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0215.jpg" alt="Lakeway"></a></div><div class="text_area"><div class="prod_name">Lakeway</div><div class="prod_desc"><div class="ExternalClass95E3134A48E84F45A9E53BFC7C25041F"><p>&#8203;3/4"-thick, mitered frame with notched outside edges&nbsp;and molded door
profile. Recessed veneer center panel&nbsp;with 2-1/2" wide rails and stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Contemporary,Transitional" data-materials="Wood" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=55"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0180.jpg" alt="Lauderdale"></a></div><div class="text_area"><div class="prod_name">Lauderdale</div><div class="prod_desc"><div class="ExternalClass2C73C9E6A8D8458883BAA904D8904000"><p>&#8203;3/4"-thick, mortise-and-tenon frame with eased outside edge detail&nbsp;and
decorative inset applied molding. Wood veneer, recessed&nbsp;center&nbsp;panel
with 3" wide rails and stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Arts and Crafts,Traditional" data-materials="Thermofoil" data-construction="Raised Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=56"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0037.jpg" alt="Lexington"></a></div><div class="text_area"><div class="prod_name">Lexington</div><div class="prod_desc"><div class="ExternalClass02FFB3122E8A4FB89C60A5091462158D"><p>&#8203;3/4"-thick, slant-bevel, small-stepped raised panel door and&nbsp;drawer
front with small-stepped edge detail on inside frame&nbsp;edge and ogee
detail on outside edges. 1-3/4" rails and stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Traditional" data-materials="Wood" data-construction="Raised Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=57"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0016.jpg" alt="Liberty"></a></div><div class="text_area"><div class="prod_name">Liberty</div><div class="prod_desc"><div class="ExternalClass45E19CB89EEF4B3094F936182905E21D"><p>&#8203;3/4"-thick, mitered frame with molded profile. Solid&nbsp;wood, slant-bevel, raised center panel. 2-7/8" wide&nbsp;rails and stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Traditional" data-materials="Wood" data-construction="Raised Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=58"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0121.jpg" alt="Livingston"></a></div><div class="text_area"><div class="prod_name">Livingston</div><div class="prod_desc"><div class="ExternalClassABFA897421CF4CEC944E2B783A2A1C86"><p>&#8203;3/4"-thick, mitered frame with molded profile. Solid&nbsp;wood, raised center panel. 2-15/16" wide rails and stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Traditional" data-materials="Wood" data-construction="Raised Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=59"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0015.jpg" alt="Manhattan Wide"></a></div><div class="text_area"><div class="prod_name">Manhattan Wide</div><div class="prod_desc"><div class="ExternalClassC89426F036AD4FF0B894AB7177BC9F55"><p>&#8203;3/4"-thick, mortise-and-tenon frame with ogee detail on&nbsp;outside and
inside edge, applied molding detail, and 3-1/2"&nbsp;wide rails and stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Arts and Crafts,Contemporary,Transitional" data-materials="Wood" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=101"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/Marshall%20Slab%20Cherry%20Platinum%20Grey%20Flat.jpg" alt="Marshall"></a></div><div class="text_area"><div class="prod_name">Marshall</div><div class="prod_desc"><div class="ExternalClass3896660E3A554AF981025691CD166282"><p>3/4˝-wide,&nbsp;mitered frame with eased outside edge. Veneer center&nbsp;panel is recessed only 1/8˝. Slab drawer front standard, 5-piece Matching Drawer Front optional.</p><p><br></p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Contemporary,Modern" data-materials="Melamine" data-construction="Slab"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=60"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0220.jpg" alt="Martin"></a></div><div class="text_area"><div class="prod_name">Martin</div><div class="prod_desc"><div class="ExternalClass77E0E1F597094DABAD885EA76419656B"><p>&#8203;3/4"-thick, Textured Melamine, 3-piece door and drawer front
featuring&nbsp;3˝ stiles with vertical grain and a flat center panel with
horizontal grain.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Contemporary" data-materials="Melamine" data-construction="Slab"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=61"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0136.jpg" alt="Metropolis"></a></div><div class="text_area"><div class="prod_name">Metropolis</div><div class="prod_desc"><div class="ExternalClass128F52023AD546909C9832A887F16534"><p>&#8203;This Textured Melamine door features realistic grain patterns with a
matching textured edgebanding. The back of this door features a matching
 Textured Melamine with the exception of Ebony Ash, which matches, but
does not include the texture.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Arts and Crafts,Contemporary,Transitional" data-materials="Thermofoil" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=62"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0204.jpg" alt="Mission ll"></a></div><div class="text_area"><div class="prod_name">Mission ll</div><div class="prod_desc"><div class="ExternalClass1CA3F6F4715C490D973CB1F67D782F4E"><p>&#8203;3/4"-thick, recessed-panel door and slab&nbsp;drawer front with eased outside edges.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Traditional" data-materials="Wood" data-construction="Raised Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=64"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0014.jpg" alt="Mount Vernon"></a></div><div class="text_area"><div class="prod_name">Mount Vernon</div><div class="prod_desc"><div class="ExternalClassF04A991630584FEDAB5372D9A7466EB0"><p>&#8203;3/4"-thick, mitered frame with detailed, molded profile.&nbsp;Solid wood,
slant-bevel, raised center panel. 2-1/2" wide&nbsp;rails and stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Contemporary,Transitional" data-materials="Wood" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=66"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0131.jpg" alt="Oakland Park"></a></div><div class="text_area"><div class="prod_name">Oakland Park</div><div class="prod_desc"><div class="ExternalClassFC73F4E5899D4E779DF4A1B88D6B2A4B"><p>&#8203;3/4"-thick, mitered frame with eased outside edge and&nbsp;beveled inside
edge door profile. Veneer, recessed center&nbsp;panel with 2-11/16” wide
rails and stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Traditional,Transitional" data-materials="Wood" data-construction="Raised Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=67"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0013.jpg" alt="Old Salem Wide"></a></div><div class="text_area"><div class="prod_name">Old Salem Wide</div><div class="prod_desc"><div class="ExternalClass394EC060CA5346DF9F5D4E60FE50E3AC"><p>&#8203;3/4"-thick, mortise-and-tenon frame with ogee detail on
outside&nbsp;and&nbsp;inside edge, and 3-1/2" wide rails and stiles.
Solid&nbsp;wood,&nbsp;slant-bevel, raised center panel.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Contemporary,Modern" data-materials="Thermofoil" data-construction="Slab"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=68"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0084.jpg" alt="Pasadena"></a></div><div class="text_area"><div class="prod_name">Pasadena</div><div class="prod_desc"><div class="ExternalClassE21F988376824C4C9A83D336B815A68B"><p>&#8203;3/4"-thick, slab door and drawer front with beveled horizontal edges.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Traditional" data-materials="Wood" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=69"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0188.jpg" alt="Perth Amboy"></a></div><div class="text_area"><div class="prod_name">Perth Amboy</div><div class="prod_desc"><div class="ExternalClass4582A8FBDF0344DF9690C04268168D93"><p>&#8203;3/4"-thick, mitered frame with eased outside edge, beading on&nbsp;inside
edge for an inset look, and 3-7/8" wide rails and stiles.&nbsp;Solid wood,
slant-bevel, raised center panel.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Traditional,Transitional" data-materials="Eurotek Veneer" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=70"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0059.jpg" alt="Philadelphia"></a></div><div class="text_area"><div class="prod_name">Philadelphia</div><div class="prod_desc"><div class="ExternalClass4C354AF3C534417E893ED01719E98A21"><p>&#8203;3/4"-thick, recessed-panel door with eased outside&nbsp;edges, ogee&nbsp;inside edge and 3-1⁄8"-wide rails and stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Contemporary,Modern" data-materials="Melamine" data-construction="Slab"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=71"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0122.jpg" alt="Piper"></a></div><div class="text_area"><div class="prod_name">Piper</div><div class="prod_desc"><div class="ExternalClassA5E4D3FCE6BA4A6EBB2FDAFAB1B4130C"><p>&#8203;3/4"-thick, slab door &amp; drawer front with square edges.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Arts and Crafts,Contemporary,Transitional" data-materials="Wood" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=72"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0091.jpg" alt="Plainview"></a></div><div class="text_area"><div class="prod_name">Plainview</div><div class="prod_desc"><div class="ExternalClassC4ED29F76D9942749206D9074F81726A"><p>&#8203;3/4"-thick, mortise-and-tenon frame with eased edges, and&nbsp;2-5/16" wide
rails and stiles. Veneer, shallow-depth recessed&nbsp;center panel.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Arts and Crafts,Contemporary,Transitional" data-materials="Wood" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=73"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0089.jpg" alt="Plainview Wide"></a></div><div class="text_area"><div class="prod_name">Plainview Wide</div><div class="prod_desc"><div class="ExternalClass95E2B6025B664465BFA5CBF650F4F1FD"><p>&#8203;3/4"-thick, mortise-and-tenon frame with eased edges, and -31/2" wide
rails and stiles. Veneer, shallow-depth recessed&nbsp;center panel.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Contemporary,Transitional" data-materials="Wood" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=74"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0124.jpg" alt="Plantation"></a></div><div class="text_area"><div class="prod_name">Plantation</div><div class="prod_desc"><div class="ExternalClass8D8759B3A756469C96842D1DF65FB388"><p>&#8203;3/4"-thick, mortise-and-tenon frame with eased inside&nbsp;edges and large
beveled outside edge. Solid wood,&nbsp;recessed center panel. 3"&nbsp;wide rails
and stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Traditional" data-materials="Wood" data-construction="Raised Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=75"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0093.jpg" alt="Plymouth"></a></div><div class="text_area"><div class="prod_name">Plymouth</div><div class="prod_desc"><div class="ExternalClass37AE3056128448F183D386578C0C503D"><p>&#8203;3/4"-thick, mitered and beaded frame with applied molding&nbsp;detail. Solid
wood, detailed, raised center panel. 2-1/4" wide&nbsp;rails and stiles. </p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Traditional" data-materials="Wood" data-construction="Raised Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=77"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0027.jpg" alt="Raised"></a></div><div class="text_area"><div class="prod_name">Raised</div><div class="prod_desc"><div class="ExternalClassD75075289B334D4DBE93577A39D53B6F"><p>&#8203;3/4"-thick, mortise-and-tenon frame with eased outer&nbsp;edges. Solid Wood,
cove-bevel, raised center&nbsp;panel.&nbsp;2-1/2" wide rails and stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Contemporary,Transitional" data-materials="Wood" data-construction="Slab"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=78"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/Richmond-II-Walnut-Natural.jpg" alt="Richmond II"></a></div><div class="text_area"><div class="prod_name">Richmond II</div><div class="prod_desc"><div class="ExternalClass3850726FD36D41F4BE1A960EEE022EF8"><p>&#8203;3/4"-thick, slab with eased edges. Vertical-grain veneer&nbsp;with 3mm solid wood edgebanding on all edges.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Arts and Crafts,Contemporary,Transitional" data-materials="Wood" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=102"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/Wood%20-%20Ridgecrest%20Slab%20-%20Pebble%20Grey%20paint%20-%20Flat.jpg" alt="Ridgecrest"></a></div><div class="text_area"><div class="prod_name">Ridgecrest</div><div class="prod_desc"><div class="ExternalClassBD05FBE1662F4AE0B37794BEA9402D78"><p>3/4"-thick, mortise-and-tenon frame with eased edges.&nbsp;Veneer, recessed center panel. 25/16" wide rails and stiles.&nbsp;Slab drawer front with horizontal grain standard.<br></p><p><br></p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Contemporary,Transitional" data-materials="Wood" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=79"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0096.jpg" alt="Rockford"></a></div><div class="text_area"><div class="prod_name">Rockford</div><div class="prod_desc"><div class="ExternalClassF691D1F4A98C40D592F3CC61F3086C22"><p>&#8203;3/4"-thick, mortise-and-tenon frame with eased outside edge&nbsp;and beaded
inside edge detail. Wood veneer, recessed center&nbsp;panel with 2-5/16˝ wide
 rails and stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Traditional" data-materials="Wood" data-construction="Raised Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=80"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0103.jpg" alt="Royalton"></a></div><div class="text_area"><div class="prod_name">Royalton</div><div class="prod_desc"><div class="ExternalClass10BE0277232E4A249211B423B5152119"><p>&#8203;3/4" thick, Mortise and Tenon frame with elongated ogee outside&nbsp;profile
and modified bead inside edge. Solid wood, step and&nbsp;cover raised center
panel with 3-1/2" &nbsp;wide rails and stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Contemporary,Transitional" data-materials="Wood" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=81"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0194.jpg" alt="Sagamore"></a></div><div class="text_area"><div class="prod_name">Sagamore</div><div class="prod_desc"><div class="ExternalClassEF061BC3B3C646709B12A4735259C4D5"><p>&#8203;3/4"-thick, mortise-and-tenon frame with eased outside edge&nbsp;and beaded
inside edge detail. Solid wood, recessed center&nbsp;panel with 2- 5/16˝ wide
 rails and stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Contemporary,Transitional" data-materials="Wood" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=82"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0104.jpg" alt="Sarasota"></a></div><div class="text_area"><div class="prod_name">Sarasota</div><div class="prod_desc"><div class="ExternalClass2FA06DCD90FA44D3BE7061B66C576E57"><p>&#8203;3/4"-thick, mitered frame with eased outside edge and
flat&nbsp;stepped&nbsp;inside edge. Solid wood, recessed center panel with&nbsp;3-1/4˝
wide rails and stiles (including inside edge detail).</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Contemporary,Modern" data-materials="Melamine" data-construction="Slab"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=83"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0002.jpg" alt="Seneca"></a></div><div class="text_area"><div class="prod_name">Seneca</div><div class="prod_desc"><div class="ExternalClass1F51E21FD1E646439143D63357B3776A"><p>&#8203;3/4"-thick, slab door &amp; drawer front with square edges.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Arts and Crafts,Contemporary,Transitional" data-materials="Wood" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=84"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/Shaker-Walnut-Natural.jpg" alt="Shaker"></a></div><div class="text_area"><div class="prod_name">Shaker</div><div class="prod_desc"><div class="ExternalClass1E89AF0599FB4F8EA3E4634FA10E2AFE"><p>&#8203;3/4"-thick, mortise-and-tenon frame with eased&nbsp;edges.&nbsp;Veneer,&nbsp;recessed center panel. 25/16" wide rails and stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Arts and Crafts,Contemporary,Transitional" data-materials="Wood" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=85"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0008.jpg" alt="Shaker Wide"></a></div><div class="text_area"><div class="prod_name">Shaker Wide</div><div class="prod_desc"><div class="ExternalClass74B941469DE84F69924B346E8085EB51"><p>&#8203;3/4"-thick, mortise-and-tenon frame with eased edges, and&nbsp;3-1/2"&nbsp;wide rails and stiles. Veneer, recessed center panel. </p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Contemporary,Modern" data-materials="Wood" data-construction="Slab"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=86"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/Slab-Oak-Storm-Grey.jpg" alt="Slab"></a></div><div class="text_area"><div class="prod_name">Slab</div><div class="prod_desc"><div class="ExternalClass9113816631EF4F6D8E28615A3C911B8B"><p>&#8203;3/4"-thick slab with square edges. Horizontal- or vertical-grain&nbsp;veneer
with veneer edgebanding on all edges. Slab drawer front&nbsp;with horizontal
or vertical grain.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Contemporary,Modern" data-materials="Deluxe Veneers" data-construction="Slab"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=87"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/Slab-RiftCutOak-Natural.jpg" alt="Slab - Deluxe Veneer"></a></div><div class="text_area"><div class="prod_name">Slab - Deluxe Veneer</div><div class="prod_desc"><div class="ExternalClass3CBD8EF5D1524669B34E6602CBAE8A49"><p>&#8203;3/4"-thick slab with square edges. Horizontal- or vertical-grain&nbsp;veneer with veneer edgebanding on all edges.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Contemporary,Modern" data-materials="Metal" data-construction="Slab"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=88"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0005.jpg" alt="Slimline Aluminum"></a></div><div class="text_area"><div class="prod_name">Slimline Aluminum</div><div class="prod_desc"><div class="ExternalClassE85FB26E2D334B47A882D667D25C21F5"><p>The <strong>Slimline Aluminum</strong> Door Style features a mitered aluminum frame with a choice of&nbsp;opaque acrylic or glass inserts.&nbsp;&nbsp;The
 acrylic or glass insert covers a majority of the frame and only a small
 slim area of the aluminum rests above the insert, creating a sleek
modern look.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Contemporary,Modern" data-materials="UltraLux" data-construction="Slab"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=89"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0135.jpg" alt="South Beach"></a></div><div class="text_area"><div class="prod_name">South Beach</div><div class="prod_desc"><div class="ExternalClass9AC8AD70242D43A68A54CB6C63422958"><p>&#8203;This UltraLux door features a High Gloss Acrylic front with&nbsp;matching
laser edgebanding.&nbsp;UltraLux finishes (with the exception of the
Linear&nbsp;options) are scratch-resistant.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Arts and Crafts,Contemporary,Transitional" data-materials="Wood" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=90"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0035.jpg" alt="Stickley"></a></div><div class="text_area"><div class="prod_name">Stickley</div><div class="prod_desc"><div class="ExternalClass231E0DB493084E9AB1764952B37BAEFD"><p>&#8203;3/4"-thick, mortise-and-tenon frame with eased&nbsp;edges. Solid wood, recessed&nbsp;center panel. 2-5/16"&nbsp;wide rails and stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Arts and Crafts,Contemporary,Transitional" data-materials="Wood" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=91"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0024.jpg" alt="Stickley Wide"></a></div><div class="text_area"><div class="prod_name">Stickley Wide</div><div class="prod_desc"><div class="ExternalClass21973A48AE1F4B85A6D8FAC97070ED4E"><p>&#8203;3/4"-thick, mortise-and-tenon frame with eased edges,&nbsp;and 3-1/2" wide rails and stiles. Solid wood, recessed&nbsp;center panel.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Arts and Crafts,Contemporary,Modern,Southwest,Transitional" data-materials="Wood" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=95"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0252.jpg" alt="Wicker Park"></a></div><div class="text_area"><div class="prod_name">Wicker Park</div><div class="prod_desc"><div class="ExternalClass1627C88195CA4D1EB426CB31639C3A44"><p>&#8203;3/4"-thick, mortise and tenon recessed panel door with RO outside
profile and single step inside molding. Features a reverse raised
recessed center panel, with 2-3/4" wide rails and stiles (including
step).</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Traditional" data-materials="Wood" data-construction="Recessed Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=96"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0133.jpg" alt="Winchester"></a></div><div class="text_area"><div class="prod_name">Winchester</div><div class="prod_desc"><div class="ExternalClass084DF13D57A14E25904623009C46A0D6"><p>&#8203;3/4"-thick, mitered frame with eased outside edge&nbsp;and molded door
profile. Solid wood, recessed center&nbsp;panel with 2 15/16”” wide rails and
 stiles.</p></div></div></div></div><div class="col-md-4 mt-3 door-card" data-styles="Traditional" data-materials="Wood" data-construction="Raised Panel"><div class="image_area"><a target="_blank" href="https://www.europacabinetry.com/door_details?id=97"><img class="lazyload door_img" style="width:79px; height:160px;" data-src="https://authoring.norcraftcompanies.com/UltraCraft/Door%20Images/0094.jpg" alt="York"></a></div><div class="text_area"><div class="prod_name">York</div><div class="prod_desc"><div class="ExternalClass3EC5197F5A184E67A1F78447B2965637"><p>&#8203;3/4"-thick, mitered and beaded frame with profiled molding&nbsp;detail. Solid
 wood, detailed, raised center panel. 2-1/2" wide&nbsp;rails and stiles.</p></div></div></div></div></div>
        </div>
